### ISSUE TITLE
2dgs with depth and scale reularization

### ISSUE THREAD

**Issue by Kapilthakur1520** [yzslab/gaussian-splatting-lightning#124]
How can we train the 2dgs model with depth regularization and scale regularization.
Is it as simple as changing the config file if yes how 
and where do i need to make the changes

**Comment by yzslab** [comment]
Significant updates to [`GS2DMetrics`](https://github.com/yzslab/gaussian-splatting-lightning/blob/main/internal/metrics/gs2d_metrics.py) are required.

**Comment by yashj235** [comment]
Hey, this is what I did for 2DGS + depth regularization. I am not sure what you mean by scale regularization. 

Copy citygsv2_metrics.py from [here](https://github.com/DekuLiuTesla/CityGaussian/blob/main/internal/metrics/citygsv2_metrics.py) to internals/metrics


This is how my config looks like (again inspired from citygaussians but slight differences)

```
data:
  parser: internal.dataparsers.estimated_depth_colmap_dataparser.EstimatedDepthColmap
  val_max_num_images_to_cache: -1
  test_max_num_images_to_cache: -1
model:
  gaussian: 
    class_path: internal.models.gaussian_2d.Gaussian2D
    init_args:
      sh_degree: 2
  renderer: internal.renderers.vanilla_2dgs_renderer.Vanilla2DGSRenderer
  metric: 
    class_path: internal.metrics.citygsv2_metrics.CityGSV2Metrics
    init_args:
      lambda_normal: 0.0125
      depth_loss_type: l1+ssim
      depth_loss_ssim_weight: 1.0
      depth_loss_weight:
        init: 0.5
        final_factor: 0.005
  density:
    class_path: internal.density_controllers.gs2d_density_controller.GS2DDensityController
    init_args:
      cull_opacity_threshold: 0.05
```

This worked well for me and helped me reconstruct scenes from aerial images more accurately. You can try it. You can change parameters from config file for your need. Depth loss of l1 type is preferred normally.

**Comment by songsenIng** [comment]
> Hey, this is what I did for 2DGS + depth regularization. I am not sure what you mean by scale regularization.
> 
> Copy citygsv2_metrics.py from [here](https://github.com/DekuLiuTesla/CityGaussian/blob/main/internal/metrics/citygsv2_metrics.py) to internals/metrics
> 
> This is how my config looks like (again inspired from citygaussians but slight differences)
> 
> ```
> data:
>   parser: internal.dataparsers.estimated_depth_colmap_dataparser.EstimatedDepthColmap
>   val_max_num_images_to_cache: -1
>   test_max_num_images_to_cache: -1
> model:
>   gaussian: 
>     class_path: internal.models.gaussian_2d.Gaussian2D
>     init_args:
>       sh_degree: 2
>   renderer: internal.renderers.vanilla_2dgs_renderer.Vanilla2DGSRenderer
>   metric: 
>     class_path: internal.metrics.citygsv2_metrics.CityGSV2Metrics
>     init_args:
>       lambda_normal: 0.0125
>       depth_loss_type: l1+ssim
>       depth_loss_ssim_weight: 1.0
>       depth_loss_weight:
>         init: 0.5
>         final_factor: 0.005
>   density:
>     class_path: internal.density_controllers.gs2d_density_controller.GS2DDensityController
>     init_args:
>       cull_opacity_threshold: 0.05
> ```
> 
> This worked well for me and helped me reconstruct scenes from aerial images more accurately. You can try it. You can change parameters from config file for your need. Depth loss of l1 type is preferred normally.

Where should these codes be placed and how should I use them? Sincerely looking forward to your reply. Thank you.

```
data:
  parser: internal.dataparsers.estimated_depth_colmap_dataparser.EstimatedDepthColmap
  val_max_num_images_to_cache: -1
  test_max_num_images_to_cache: -1
model:
  gaussian: 
    class_path: internal.models.gaussian_2d.Gaussian2D
    init_args:
      sh_degree: 2
  renderer: internal.renderers.vanilla_2dgs_renderer.Vanilla2DGSRenderer
  metric: 
    class_path: internal.metrics.citygsv2_metrics.CityGSV2Metrics
    init_args:
      lambda_normal: 0.0125
      depth_loss_type: l1+ssim
      depth_loss_ssim_weight: 1.0
      depth_loss_weight:
        init: 0.5
        final_factor: 0.005
  density:
    class_path: internal.density_controllers.gs2d_density_controller.GS2DDensityController
    init_args:
      cull_opacity_threshold: 0.05
```
