### ISSUE TITLE
Light Gaussian with gsplat absgs

### ISSUE THREAD

**Issue by hardikdava** [yzslab/gaussian-splatting-lightning#31]
Hello, is it possible to train a model with a combination of gsplat absgs and light gaussian? Thanks

**Comment by yzslab** [comment]
Of course. Here is a example config file:
```yaml
model:
  gaussian:
    optimization:
      densify_grad_threshold: 0.0006
  renderer: internal.renderers.gsplat_renderer.GSPlatRenderer
  absgrad: true
  light_gaussian:
    prune_decay: 0.6
    prune_percent: 0.6
    prune_steps:
      - 16_000
      - 24_000
```
