### ISSUE TITLE
PLY cannot opened in Supersplat or Mkkellogg gaussian viewer

### ISSUE THREAD

**Issue by ichsan2895** [yzslab/gaussian-splatting-lightning#32]
What I have run
```
# Single GPU at the beginning
>>> python3 main.py fit \
    --config configs/gsplat-absgrad-sphere.yaml \
    --data.path 'DATASET/KERINCI_PEAK_convertINRIA' \
    --data.type colmap \
    --model.gaussian.optimization.densify_until_iter 15000 \
    --max_steps 15000 --logger wandb

Validation:   0%|                                         | 0/8 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|                            | 0/8 [00:00<?, ?it/s]
Validation DataLoader 0:  12%|██▌                 | 1/8 [00:00<00:00, 42.05it/s]
Validation DataLoader 0:  25%|█████               | 2/8 [00:00<00:00, 38.87it/s]
Validation DataLoader 0:  38%|███████▌            | 3/8 [00:00<00:00, 33.95it/s]
Validation DataLoader 0:  50%|██████████          | 4/8 [00:00<00:00, 32.51it/s]
Validation DataLoader 0:  62%|████████████▌       | 5/8 [00:00<00:00, 20.37it/s]
Validation DataLoader 0:  75%|███████████████     | 6/8 [00:00<00:00, 18.66it/s]
Validation DataLoader 0:  88%|█████████████████▌  | 7/8 [00:00<00:00, 20.00it/s]
Validation DataLoader 0: 100%|████████████████████| 8/8 [00:00<00:00, 20.51it/s]
Epoch 238:  10%| | 6/63 [00:00<00:07,  7.53it/s, v_num=0, train/loss=0.0241, val`Trainer.fit` stopped: `max_steps=15000` reached.
Checkpoint saved to /workspace/YZLAB_LIGHTNING/gaussian-splatting-lightning/outputs/MY_DATASET/checkpoints/epoch=239-step=15000.ckpt
Epoch 238:  10%| | 6/63 [00:22<03:31,  3.71s/it, v_num=0, train/loss=0.0241, val
```

The content of `configs/gsplat-absgrad-sphere.yaml`
```
data:
  params:
    val_max_num_images_to_cache: -1
    test_max_num_images_to_cache: -1
    add_background_sphere: true
    background_sphere_distance: 2.2
    background_sphere_points: 204800
model:
  gaussian:
    optimization:
      densify_grad_threshold: 0.0006
  renderer: internal.renderers.gsplat_renderer.GSPlatRenderer
  absgrad: true
```

I open the file at `outputs/MY_DATASET/checkpoints/epoch=478-step=30000-preview.ply` with [mkellogg gaussian viewer](https://projects.markkellogg.org/threejs/demo_gaussian_splats_3d.php) and/or [supersplat playcanvas](https://playcanvas.com/supersplat/editor/). Both gives empty result.
![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/60387342/fdfb68c1-ec7f-4f6a-8604-2d72387fa70f)

additional information:
```
RTX A6000 48 GB
Ubuntu 22.04.3 LTS
python 3.10.12
torch 2.0.1+cu118
lightning 2.0.9.post0
gsplat 0.1.12
gaussian-splatting-lightning@8697d830ed4cfcf3ed9facc78256e3d1a5e0c423
```

FYI, this command gives good result
```
python viewer.py 'outputs/MY_DATASET' --port 7008
```
![image](https://github.com/yzslab/gaussian-splatting-lightning/assets/60387342/0bb0ac20-9f21-4124-92da-0d674cb0c6ec)
